<?php

/**
 * Component Less Builder.
 *
 * Assembles complete Less source for a component by combining:
 * - UIkit base variables
 * - UIkit mixins
 * - YOOtheme theme variables
 * - Our consolidated variables
 * - UIkit component Less (with CSS rules)
 * - User variable overrides
 *
 * @package Enhanced_Plugin_Bundle
 * @since 4.2.0
 */

namespace EPB\CSS;

/**
 * Component Less Builder class.
 */
class Component_Less_Builder
{

    /**
     * Path to YOOtheme's UIkit source.
     *
     * @var string
     */
    private string $uikit_path;

    /**
     * Path to YOOtheme's theme Less files.
     *
     * @var string
     */
    private string $yootheme_path;

    /**
     * Path to our consolidated Less files.
     *
     * @var string
     */
    private string $consolidated_path;

    /**
     * Constructor.
     */
    public function __construct()
    {
        // Use wp_normalize_path for cross-platform compatibility
        $this->uikit_path = wp_normalize_path(WP_CONTENT_DIR . '/themes/yootheme/vendor/assets/uikit/src/less/');
        $this->yootheme_path = wp_normalize_path(WP_CONTENT_DIR . '/themes/yootheme/less/');
        $this->consolidated_path = wp_normalize_path(EPB_PLUGIN_DIR . 'docs/uikit-less-consolidated/');
    }

    /**
     * Check if the required source files exist.
     *
     * @return bool|string True if ready, or error message.
     */
    public function check_requirements()
    {
        if (!is_dir($this->uikit_path)) {
            return 'YOOtheme UIkit source not found at: ' . $this->uikit_path;
        }

        if (!is_dir($this->uikit_path . 'components/')) {
            return 'UIkit components folder not found';
        }

        if (!is_dir($this->consolidated_path)) {
            return 'Consolidated Less files not found. Please run the consolidation script.';
        }

        return true;
    }

    /**
     * Build complete Less source for a component.
     *
     * @param string $component The component name (e.g., 'button', 'card').
     * @param array  $overrides Optional. Variable overrides from user.
     * @return string|false The complete Less source, or false on failure.
     */
    public function build(string $component, array $overrides = [])
    {
        $check = $this->check_requirements();
        if ($check !== true) {
            return false;
        }

        $component = sanitize_key($component);

        // Check if UIkit component exists.
        $uikit_component_file = $this->uikit_path . 'components/' . $component . '.less';
        if (!file_exists($uikit_component_file)) {
            return false;
        }

        $parts = [];

        // 1. All consolidated variables (from _all-variables.less - includes all UIkit + YOOtheme vars).
        $parts[] = $this->get_all_consolidated_variables();

        // 2. UIkit mixins.
        $parts[] = $this->get_uikit_mixins();

        // 3. Generate empty hook stubs (to prevent undefined mixin errors).
        $parts[] = $this->generate_hook_stubs($component);

        // 4. UIkit component Less (contains CSS rules).
        $parts[] = $this->get_uikit_component($component);

        // 5. User variable overrides (LAST - highest priority).
        if (!empty($overrides)) {
            $parts[] = $this->generate_overrides($overrides);
        }

        return implode("\n\n", array_filter($parts));
    }

    /**
     * Build Less source for preview (simplified version with faster compilation).
     *
     * @param string $component The component name.
     * @param array  $overrides Variable overrides from user.
     * @return string|false The Less source, or false on failure.
     */
    public function build_for_preview(string $component, array $overrides = [])
    {
        // For preview, we use the same build process.
        // In the future, we could optimize by caching the base content.
        return $this->build($component, $overrides);
    }

    /**
     * Get all consolidated variables from _all-variables.less.
     *
     * This file contains ALL variables from all components, including
     * UIkit defaults and YOOtheme-specific additions. Generated by
     * the consolidation script.
     *
     * @return string
     */
    private function get_all_consolidated_variables(): string
    {
        $file = $this->consolidated_path . '_all-variables.less';

        if (file_exists($file)) {
            $content = file_get_contents($file);

            // Filter out mixin-local variables that shouldn't be at top level
            // These are local vars inside Less mixins (svg-fill, etc.)
            $lines = explode("\n", $content);
            $filtered = [];
            $skip_patterns = [
                '/^@data-uri\s*:/',
                '/^@escape-/',
                '/^@replace-/',
            ];

            foreach ($lines as $line) {
                $skip = false;
                foreach ($skip_patterns as $pattern) {
                    if (preg_match($pattern, trim($line))) {
                        $skip = true;
                        break;
                    }
                }
                if (!$skip) {
                    $filtered[] = $line;
                }
            }

            return "// All Consolidated Variables\n" . implode("\n", $filtered);
        }

        // Fall back to individual files if _all-variables.less doesn't exist
        return $this->get_uikit_variables();
    }

    /**
     * Get UIkit base variables (fallback).
     *
     * @return string
     */
    private function get_uikit_variables(): string
    {
        $file = $this->consolidated_path . 'variables.less';

        if (!file_exists($file)) {
            $file = $this->uikit_path . 'components/variables.less';
        }

        if (file_exists($file)) {
            return "// Base Variables\n" . file_get_contents($file);
        }

        return '';
    }

    /**
     * Get UIkit mixins.
     *
     * @return string
     */
    private function get_uikit_mixins(): string
    {
        $file = $this->uikit_path . 'components/mixin.less';
        if (file_exists($file)) {
            return "// UIkit Mixins\n" . file_get_contents($file);
        }

        return '';
    }

    /**
     * Get UIkit component Less file (contains CSS rules).
     *
     * @param string $component The component name.
     * @return string
     */
    private function get_uikit_component(string $component): string
    {
        $file = $this->uikit_path . 'components/' . $component . '.less';
        if (file_exists($file)) {
            return "// UIkit Component: {$component}\n" . file_get_contents($file);
        }

        return '';
    }

    /**
     * Generate empty hook stubs to prevent undefined mixin errors.
     *
     * @param string $component The component name.
     * @return string
     */
    private function generate_hook_stubs(string $component): string
    {
        $hooks = [];

        // Read the component file and extract hook calls.
        $component_file = $this->uikit_path . 'components/' . $component . '.less';
        if (file_exists($component_file)) {
            $content = file_get_contents($component_file);
            preg_match_all('/\.(hook-[a-z0-9-]+)\(\)/', $content, $matches);
            if (!empty($matches[1])) {
                $hooks = array_merge($hooks, $matches[1]);
            }
        }

        // Also check inverse.less for hooks.
        $inverse_file = $this->uikit_path . 'components/inverse.less';
        if (file_exists($inverse_file)) {
            $content = file_get_contents($inverse_file);
            preg_match_all('/\.(hook-[a-z0-9-]+)\(\)/', $content, $matches);
            if (!empty($matches[1])) {
                $hooks = array_merge($hooks, $matches[1]);
            }
        }

        // Generate empty hook definitions.
        $hooks = array_unique($hooks);
        if (empty($hooks)) {
            return '';
        }

        $stubs = "// Empty Hook Stubs\n";
        foreach ($hooks as $hook) {
            $stubs .= ".{$hook}() {}\n";
        }

        return $stubs;
    }

    /**
     * Generate Less variable override string from an array.
     *
     * @param array $overrides Variable name => value pairs.
     * @return string
     */
    private function generate_overrides(array $overrides): string
    {
        $lines = ["// User Variable Overrides"];

        foreach ($overrides as $name => $value) {
            // Sanitize variable name.
            $name = preg_replace('/[^a-zA-Z0-9_-]/', '', $name);
            if (empty($name) || empty($value)) {
                continue;
            }

            // Don't add @ prefix if already present.
            if (strpos($name, '@') !== 0) {
                $name = '@' . $name;
            }

            $lines[] = "{$name}: {$value};";
        }

        return implode("\n", $lines);
    }

    /**
     * Get list of available components from the UIkit source directory.
     *
     * Returns component names from the YOOtheme UIkit Less source files.
     *
     * @return array<string> List of component names.
     */
    public function get_uikit_source_components(): array
    {
        $components = [];

        $dir = $this->uikit_path . 'components/';
        if (is_dir($dir)) {
            foreach (glob($dir . '*.less') as $file) {
                $name = basename($file, '.less');
                // Skip special files.
                if (!in_array($name, ['_import', 'variables', 'mixin'], true)) {
                    $components[] = $name;
                }
            }
        }

        sort($components);
        return $components;
    }
}
