<?php

/**
 * Plugin Constants for Enhanced Plugin Bundle.
 *
 * Centralized location for all plugin constants to avoid duplication.
 *
 * @package Enhanced_Plugin_Bundle
 * @subpackage Core
 * @since 4.2.0
 */

namespace EPB\Core;

// Prevent direct access.
if (!defined('ABSPATH')) {
    header('Status: 403 Forbidden');
    header('HTTP/1.1 403 Forbidden');
    exit();
}

/**
 * Class Constants
 *
 * Defines all plugin-wide constants in a single location.
 */
class Constants
{
    /**
     * Option prefix for component storage in wp_options.
     *
     * @var string
     */
    public const OPTION_PREFIX = 'epb_component_';

    /**
     * Nonce action for component AJAX operations.
     *
     * @var string
     */
    public const NONCE_ACTION = 'epb_component_nonce';

    /**
     * Transient key for cached component CSS.
     *
     * @var string
     */
    public const TRANSIENT_CSS = 'epb_component_css';

    /**
     * Cache duration for component CSS transient (1 hour).
     *
     * @var int
     */
    public const CACHE_DURATION = HOUR_IN_SECONDS;

    /**
     * Option key for the general fluid typography scale ratio.
     *
     * @var string
     */
    public const OPTION_FLUID_SCALE_RATIO = 'epb_fluid_scale_ratio';

    /**
     * Option key for the navbar fluid typography scale ratio.
     *
     * @var string
     */
    public const OPTION_FLUID_SCALE_RATIO_NAVBAR = 'epb_fluid_scale_ratio_navbar';

    /**
     * Option key for the nav fluid typography scale ratio.
     *
     * @var string
     */
    public const OPTION_FLUID_SCALE_RATIO_NAV = 'epb_fluid_scale_ratio_nav';

    /**
     * Default general fluid scale ratio value.
     *
     * @var string
     */
    public const DEFAULT_FLUID_SCALE_RATIO = '0.85';

    /**
     * Default navbar fluid scale ratio value.
     *
     * @var string
     */
    public const DEFAULT_FLUID_SCALE_RATIO_NAVBAR = '0.85';

    /**
     * Default nav fluid scale ratio value.
     *
     * @var string
     */
    public const DEFAULT_FLUID_SCALE_RATIO_NAV = '0.85';

    /**
     * Option key for hyphenation & word-wrap toggle.
     *
     * @var string
     */
    public const OPTION_HYPHENATION_ENABLED = 'epb_hyphenation_enabled';

    /**
     * Option key for Adobe Font enabled toggle.
     *
     * @var string
     */
    public const OPTION_ADOBE_FONT_ENABLED = 'epb_adobe_font_enabled';

    /**
     * Option key for Adobe Font CSS URL.
     *
     * @var string
     */
    public const OPTION_ADOBE_FONT_URL = 'epb_adobe_font_url';

    /**
     * Option key for child theme branding settings.
     *
     * @var string
     */
    public const OPTION_BRANDING = 'epb_branding';

    /**
     * Default branding values.
     *
     * @var array<string, string>
     */
    public const DEFAULT_BRANDING = [
        'theme_name'   => 'CT Child',
        'company_name' => 'Plappermaul OG',
        'company_url'  => 'https://www.plappermaul.at',
        'logo_url'     => 'https://www.plappermaul.at/external/img/plappermaul_logp_green-light-1.svg',
        'description'  => 'Child theme generated by Enhanced Plugin Bundle and Theme Manager.',
        'version'      => '1.0.0',
    ];
}
